/** `keywords` is searched, never displayed; `name` is the tooltip. */

/** [char, name, keywords] */
type SymbolEntry = readonly [string, string, string];

interface SymbolGroup {
  readonly group: string;
  readonly entries: readonly SymbolEntry[];
}

export const SYMBOL_GROUPS: readonly SymbolGroup[] = [
  {
    group: "Arrows",
    entries: [
      ["→", "Right Arrow", "right direction next forward"],
      ["←", "Left Arrow", "left direction back backward"],
      ["↑", "Up Arrow", "up direction north"],
      ["↓", "Down Arrow", "down direction south"],
      ["↔", "Left Right Arrow", "horizontal both ways bidirectional"],
      ["↕", "Up Down Arrow", "vertical both ways"],
      ["↗", "North East Arrow", "diagonal up right"],
      ["↘", "South East Arrow", "diagonal down right"],
      ["↖", "North West Arrow", "diagonal up left"],
      ["↙", "South West Arrow", "diagonal down left"],
      ["⇒", "Rightwards Double Arrow", "double implies therefore"],
      ["⇐", "Leftwards Double Arrow", "double implies"],
      ["⇔", "Left Right Double Arrow", "double iff equivalent"],
      ["⟶", "Long Right Arrow", "long right"],
      ["⟵", "Long Left Arrow", "long left"],
      ["⟹", "Long Right Double Arrow", "long double right implies"],
      ["➔", "Heavy Wide Headed Right Arrow", "heavy right"],
      ["➜", "Heavy Round Tipped Right Arrow", "heavy right pointer"],
      ["➤", "Black Right Pointing Triangle", "triangle pointer right"],
      ["►", "Black Right Pointing Pointer", "triangle right play"],
      ["◄", "Black Left Pointing Pointer", "triangle left"],
      ["▲", "Black Up Pointing Triangle", "triangle up filled"],
      ["▼", "Black Down Pointing Triangle", "triangle down filled"],
      ["△", "White Up Pointing Triangle", "triangle up outline"],
      ["▽", "White Down Pointing Triangle", "triangle down outline"],
      ["↩", "Rightwards Arrow with Hook", "hook undo return"],
      ["↪", "Leftwards Arrow with Hook", "hook redo"],
      ["↵", "Downwards Arrow with Corner", "return enter newline cr"],
      [
        "⟳",
        "Clockwise Gapped Circle Arrow",
        "circle clockwise loop reload refresh",
      ],
      [
        "⟲",
        "Anticlockwise Gapped Circle Arrow",
        "circle counterclockwise undo",
      ],
      ["⇄", "Rightwards Arrow Over Leftwards", "swap exchange horizontal"],
      ["⇅", "Upwards Arrow Left Of Downwards", "swap vertical"],
    ],
  },
  {
    group: "Math",
    entries: [
      ["±", "Plus Minus Sign", "plus minus"],
      ["×", "Multiplication Sign", "multiply times cross product"],
      ["÷", "Division Sign", "divide"],
      ["≈", "Almost Equal To", "approximate equal"],
      ["≠", "Not Equal To", "not equal"],
      ["≤", "Less Than Or Equal To", "less equal"],
      ["≥", "Greater Than Or Equal To", "greater equal"],
      ["∞", "Infinity", "infinity endless"],
      ["√", "Square Root", "root radical"],
      ["∑", "N Ary Summation", "sum sigma"],
      ["∏", "N Ary Product", "product pi"],
      ["∫", "Integral", "integral calculus"],
      ["∂", "Partial Differential", "partial derivative"],
      ["∇", "Nabla", "gradient del"],
      ["∈", "Element Of", "element member belongs"],
      ["∉", "Not An Element Of", "not element"],
      ["∀", "For All", "for all universal"],
      ["∃", "There Exists", "exists existential"],
      ["∅", "Empty Set", "empty set null"],
      ["⊂", "Subset Of", "subset"],
      ["⊃", "Superset Of", "superset"],
      ["⊆", "Subset Of Or Equal To", "subset equal"],
      ["⊇", "Superset Of Or Equal To", "superset equal"],
      ["∪", "Union", "union"],
      ["∩", "Intersection", "intersection"],
      ["¬", "Not Sign", "not negation"],
      ["∧", "Logical And", "and conjunction"],
      ["∨", "Logical Or", "or disjunction"],
      ["⊕", "Circled Plus", "xor oplus"],
      ["⊗", "Circled Times", "tensor otimes"],
      ["∝", "Proportional To", "proportional"],
      ["∠", "Angle", "angle"],
      ["⊥", "Up Tack", "perpendicular orthogonal"],
      ["∥", "Parallel To", "parallel"],
      ["∴", "Therefore", "therefore"],
      ["∵", "Because", "because"],
      ["≡", "Identical To", "identical equivalent"],
      ["∼", "Tilde Operator", "tilde similar"],
      ["°", "Degree Sign", "degree temperature angle"],
      ["′", "Prime", "prime minute feet"],
      ["″", "Double Prime", "double prime second inch"],
      ["½", "Vulgar Fraction One Half", "fraction half"],
      ["¼", "Vulgar Fraction One Quarter", "fraction quarter"],
      ["¾", "Vulgar Fraction Three Quarters", "fraction"],
      ["²", "Superscript Two", "squared power"],
      ["³", "Superscript Three", "cubed power"],
      ["π", "Greek Small Letter Pi", "greek pi"],
      ["Δ", "Greek Capital Letter Delta", "greek delta change difference"],
      ["Σ", "Greek Capital Letter Sigma", "greek sigma sum"],
      ["Ω", "Greek Capital Letter Omega", "greek omega ohm"],
      ["α", "Greek Small Letter Alpha", "greek alpha"],
      ["β", "Greek Small Letter Beta", "greek beta"],
      ["λ", "Greek Small Letter Lambda", "greek lambda"],
      ["µ", "Micro Sign", "micro prefix"],
      ["θ", "Greek Small Letter Theta", "greek theta"],
      ["σ", "Greek Small Letter Sigma", "greek sigma"],
      ["ω", "Greek Small Letter Omega", "greek omega"],
    ],
  },
  {
    group: "Typographic",
    entries: [
      ["–", "En Dash", "dash punctuation range"],
      ["—", "Em Dash", "dash punctuation"],
      ["―", "Horizontal Bar", "dash horizontal bar"],
      ["‑", "Non Breaking Hyphen", "hyphen non breaking"],
      ["…", "Horizontal Ellipsis", "ellipsis dots"],
      ["•", "Bullet", "bullet list dot"],
      ["·", "Middle Dot", "dot middle"],
      ["‣", "Triangular Bullet", "bullet triangle"],
      ["▪", "Black Small Square", "bullet square"],
      [
        "«",
        "Left Pointing Double Angle Quotation Mark",
        "quote guillemet left",
      ],
      [
        "»",
        "Right Pointing Double Angle Quotation Mark",
        "quote guillemet right",
      ],
      [
        "‹",
        "Single Left Pointing Angle Quotation Mark",
        "quote single angle left",
      ],
      [
        "›",
        "Single Right Pointing Angle Quotation Mark",
        "quote single angle right",
      ],
      ["“", "Left Double Quotation Mark", "quote double left"],
      ["”", "Right Double Quotation Mark", "quote double right"],
      ["‘", "Left Single Quotation Mark", "quote single left"],
      ["’", "Right Single Quotation Mark", "quote single right apostrophe"],
      ["‚", "Single Low 9 Quotation Mark", "quote low single"],
      ["„", "Double Low 9 Quotation Mark", "quote low double"],
      ["†", "Dagger", "dagger footnote cross"],
      ["‡", "Double Dagger", "dagger double footnote"],
      ["§", "Section Sign", "section sign paragraph"],
      ["¶", "Pilcrow Sign", "paragraph sign pilcrow"],
      ["©", "Copyright Sign", "copyright"],
      ["®", "Registered Sign", "registered trademark"],
      ["™", "Trade Mark Sign", "trademark tm"],
      ["№", "Numero Sign", "number numero"],
      ["‰", "Per Mille Sign", "per mille permille"],
      ["¡", "Inverted Exclamation Mark", "exclamation inverted spanish"],
      ["¿", "Inverted Question Mark", "question inverted spanish"],
      ["℮", "Estimated Symbol", "estimated"],
      ["ª", "Feminine Ordinal Indicator", "ordinal feminine"],
      ["º", "Masculine Ordinal Indicator", "ordinal masculine"],
    ],
  },
  {
    group: "Currency",
    entries: [
      ["$", "Dollar Sign", "currency dollar usd"],
      ["€", "Euro Sign", "currency euro eur"],
      ["£", "Pound Sign", "currency pound gbp"],
      ["¥", "Yen Sign", "currency yen jpy cny"],
      ["¢", "Cent Sign", "currency cent"],
      ["₹", "Indian Rupee Sign", "currency rupee inr"],
      ["₽", "Ruble Sign", "currency ruble rub"],
      ["₩", "Won Sign", "currency won krw"],
      ["₪", "New Sheqel Sign", "currency shekel ils"],
      ["₫", "Dong Sign", "currency dong vnd"],
      ["₭", "Kip Sign", "currency kip lak"],
      ["₮", "Tugrik Sign", "currency tugrik mnt"],
      ["₱", "Peso Sign", "currency peso php"],
      ["₲", "Guarani Sign", "currency guarani pyg"],
      ["₴", "Hryvnia Sign", "currency hryvnia uah"],
      ["₵", "Cedi Sign", "currency cedi ghs"],
      ["₸", "Tenge Sign", "currency tenge kzt"],
      ["₺", "Turkish Lira Sign", "currency lira try"],
      ["₼", "Manat Sign", "currency manat azn"],
      ["₿", "Bitcoin Sign", "currency bitcoin btc"],
      ["¤", "Currency Sign", "currency generic"],
    ],
  },
  {
    group: "Enclosed",
    entries: [
      ["①", "Circled Digit One", "circled one number"],
      ["②", "Circled Digit Two", "circled two number"],
      ["③", "Circled Digit Three", "circled three number"],
      ["④", "Circled Digit Four", "circled four number"],
      ["⑤", "Circled Digit Five", "circled five number"],
      ["⑥", "Circled Digit Six", "circled six number"],
      ["⑦", "Circled Digit Seven", "circled seven number"],
      ["⑧", "Circled Digit Eight", "circled eight number"],
      ["⑨", "Circled Digit Nine", "circled nine number"],
      ["⑩", "Circled Number Ten", "circled ten number"],
      ["❶", "Dingbat Circled Digit One", "dingbat one number"],
      ["❷", "Dingbat Circled Digit Two", "dingbat two number"],
      ["❸", "Dingbat Circled Digit Three", "dingbat three number"],
      ["❹", "Dingbat Circled Digit Four", "dingbat four number"],
      ["❺", "Dingbat Circled Digit Five", "dingbat five number"],
      ["❻", "Dingbat Circled Digit Six", "dingbat six number"],
      ["❼", "Dingbat Circled Digit Seven", "dingbat seven number"],
      ["❽", "Dingbat Circled Digit Eight", "dingbat eight number"],
      ["❾", "Dingbat Circled Digit Nine", "dingbat nine number"],
      ["❿", "Dingbat Circled Digit Ten", "dingbat ten number"],
      ["Ⓐ", "Circled Latin Capital Letter A", "circled letter a"],
      ["Ⓑ", "Circled Latin Capital Letter B", "circled letter b"],
      ["ⓐ", "Circled Latin Small Letter A", "circled letter a lowercase"],
      ["ⓩ", "Circled Latin Small Letter Z", "circled letter z lowercase"],
    ],
  },
  {
    group: "Dingbats",
    entries: [
      ["✓", "Check Mark", "check tick yes done"],
      ["✔", "Heavy Check Mark", "check tick yes done"],
      ["✗", "Ballot X", "cross no wrong fail"],
      ["✘", "Heavy Ballot X", "cross no wrong fail"],
      ["☐", "Ballot Box", "checkbox empty unchecked"],
      ["☑", "Ballot Box With Check", "checkbox checked done"],
      ["☒", "Ballot Box With X", "checkbox crossed"],
      ["★", "Black Star", "star filled favourite"],
      ["☆", "White Star", "star outline favourite"],
      ["✦", "Black Four Pointed Star", "star four pointed"],
      ["✧", "White Four Pointed Star", "star four pointed outline"],
      ["✱", "Heavy Asterisk", "asterisk star"],
      ["❂", "Circled Open Centre Eight Pointed Star", "star circle eight"],
      ["❀", "White Flower", "flower blossom"],
      ["✿", "Black Florette", "flower florette"],
      ["❤", "Heavy Black Heart", "heart love red"],
      ["❥", "Rotated Heavy Black Heart Bullet", "heart love"],
      ["❦", "Floral Heart", "heart floral"],
      ["♠", "Black Spade Suit", "spade card suit"],
      ["♣", "Black Club Suit", "club card suit"],
      ["♥", "Black Heart Suit", "heart card suit"],
      ["♦", "Black Diamond Suit", "diamond card suit"],
      ["♪", "Eighth Note", "music note"],
      ["♫", "Beamed Eighth Notes", "music notes"],
      ["♬", "Beamed Sixteenth Notes", "music notes"],
      ["♭", "Music Flat Sign", "music flat"],
      ["♯", "Music Sharp Sign", "music sharp"],
      ["♮", "Music Natural Sign", "music natural"],
      ["◯", "Large Circle", "circle outline large"],
      ["◉", "Fisheye", "circle filled dot"],
      ["○", "White Circle", "circle outline"],
      ["●", "Black Circle", "circle filled dot"],
      ["◇", "White Diamond", "diamond outline"],
      ["◆", "Black Diamond", "diamond filled"],
      ["□", "White Square", "square outline"],
      ["■", "Black Square", "square filled"],
      ["⬜", "White Large Square", "square white box empty"],
      ["⬛", "Black Large Square", "square black box filled"],
    ],
  },
];
